### ISSUE TITLE
Crashing here: ...

### ISSUE THREAD

**Issue by vitalfadeev** [cerjones/dg2d#7]
https://github.com/cerjones/dg2d/blob/9e4dd66f4429121ab9098e16d8e436e937a8dffc/source/dg2d/font.d#L56

As solution I see let GC to free data...
or force destroy: m_data.destroy()

**Comment by cerjones** [comment]
Hi, if that's crashing you must be copying the font somewhere? I'd just disable the default copy constructor for now. To be honest I want to keep the core stuff GC free, so people who want that have it. So I will just disable copy constructors where relevant.
